export const ADD = "add"
export const REMOVE = "remove"
export const INITIAL = "initialIngredient"
export const AUTH_START = "Auth_Start"
export const AUTH_SUCCESS = "Auth_Success"
export const AUTH_FAILED = "Auth_Failed"